window.esdocSearchIndex = [
  [
    "@mapcreator/maps4news/src/errors/abstracterror.js~abstractclasserror",
    "class/src/errors/AbstractError.js~AbstractClassError.html",
    "<span>AbstractClassError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/AbstractError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/abstracterror.js~abstracterror",
    "class/src/errors/AbstractError.js~AbstractError.html",
    "<span>AbstractError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/AbstractError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/abstracterror.js~abstractmethoderror",
    "class/src/errors/AbstractError.js~AbstractMethodError.html",
    "<span>AbstractMethodError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/AbstractError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/apierror.js~apierror",
    "class/src/errors/ApiError.js~ApiError.html",
    "<span>ApiError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/ApiError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/choropleth.js~choropleth",
    "class/src/crud/Choropleth.js~Choropleth.html",
    "<span>Choropleth</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Choropleth.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/color.js~color",
    "class/src/crud/Color.js~Color.html",
    "<span>Color</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Color.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/contract.js~contract",
    "class/src/crud/Contract.js~Contract.html",
    "<span>Contract</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Contract.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/base/crudbase.js~crudbase",
    "class/src/crud/base/CrudBase.js~CrudBase.html",
    "<span>CrudBase</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/base/CrudBase.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/base/crudsetbase.js~crudsetbase",
    "class/src/crud/base/CrudSetBase.js~CrudSetBase.html",
    "<span>CrudSetBase</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/base/CrudSetBase.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/dimension.js~dimension",
    "class/src/crud/Dimension.js~Dimension.html",
    "<span>Dimension</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Dimension.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/dimensionset.js~dimensionset",
    "class/src/crud/DimensionSet.js~DimensionSet.html",
    "<span>DimensionSet</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/DimensionSet.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/oauth/dummyflow.js~dummyflow",
    "class/src/oauth/DummyFlow.js~DummyFlow.html",
    "<span>DummyFlow</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/oauth/DummyFlow.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/faq.js~faq",
    "class/src/crud/Faq.js~Faq.html",
    "<span>Faq</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Faq.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/feature.js~feature",
    "class/src/crud/Feature.js~Feature.html",
    "<span>Feature</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Feature.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/font.js~font",
    "class/src/crud/Font.js~Font.html",
    "<span>Font</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Font.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/fontfamily.js~fontfamily",
    "class/src/crud/FontFamily.js~FontFamily.html",
    "<span>FontFamily</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/FontFamily.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/traits/handlesimages.js~handlesimages",
    "class/src/traits/HandlesImages.js~HandlesImages.html",
    "<span>HandlesImages</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/traits/HandlesImages.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/highlight.js~highlight",
    "class/src/crud/Highlight.js~Highlight.html",
    "<span>Highlight</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Highlight.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/imagehandler.js~imagehandler",
    "class/src/ImageHandler.js~ImageHandler.html",
    "<span>ImageHandler</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/ImageHandler.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/oauth/implicitflow.js~implicitflow",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html",
    "<span>ImplicitFlow</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/oauth/ImplicitFlow.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/oauth/implicitflowpopup.js~implicitflowpopup",
    "class/src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.html",
    "<span>ImplicitFlowPopup</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/oauth/ImplicitFlowPopup.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/insetmap.js~insetmap",
    "class/src/crud/InsetMap.js~InsetMap.html",
    "<span>InsetMap</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/InsetMap.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/job.js~job",
    "class/src/crud/Job.js~Job.html",
    "<span>Job</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Job.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/jobresult.js~jobresult",
    "class/src/crud/JobResult.js~JobResult.html",
    "<span>JobResult</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/JobResult.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/jobrevision.js~jobrevision",
    "class/src/crud/JobRevision.js~JobRevision.html",
    "<span>JobRevision</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/JobRevision.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/jobshare.js~jobshare",
    "class/src/crud/JobShare.js~JobShare.html",
    "<span>JobShare</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/JobShare.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/jobtype.js~jobtype",
    "class/src/crud/JobType.js~JobType.html",
    "<span>JobType</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/JobType.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/language.js~language",
    "class/src/crud/Language.js~Language.html",
    "<span>Language</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Language.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/layer.js~layer",
    "class/src/crud/Layer.js~Layer.html",
    "<span>Layer</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Layer.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/maps4news.js~maps4news",
    "class/src/Maps4News.js~Maps4News.html",
    "<span>Maps4News</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/Maps4News.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/mapstyle.js~mapstyle",
    "class/src/crud/Mapstyle.js~Mapstyle.html",
    "<span>Mapstyle</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Mapstyle.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/mapstyleset.js~mapstyleset",
    "class/src/crud/MapstyleSet.js~MapstyleSet.html",
    "<span>MapstyleSet</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/MapstyleSet.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/nodeerror.js~nodeerror",
    "class/src/errors/NodeError.js~NodeError.html",
    "<span>NodeError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/NodeError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/notification.js~notification",
    "class/src/crud/Notification.js~Notification.html",
    "<span>Notification</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Notification.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/oauth/oauth.js~oauth",
    "class/src/oauth/OAuth.js~OAuth.html",
    "<span>OAuth</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/oauth/OAuth.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/oautherror.js~oautherror",
    "class/src/errors/OAuthError.js~OAuthError.html",
    "<span>OAuthError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/OAuthError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/oauth/oauthtoken.js~oauthtoken",
    "class/src/oauth/OAuthToken.js~OAuthToken.html",
    "<span>OAuthToken</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/oauth/OAuthToken.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/organisation.js~organisation",
    "class/src/crud/Organisation.js~Organisation.html",
    "<span>Organisation</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Organisation.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/traits/ownableresource.js~ownableresource",
    "class/src/traits/OwnableResource.js~OwnableResource.html",
    "<span>OwnableResource</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/traits/OwnableResource.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/paginatedresourcelisting.js~paginatedresourcelisting",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html",
    "<span>PaginatedResourceListing</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/PaginatedResourceListing.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/paginatedresourcewrapper.js~paginatedresourcewrapper",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html",
    "<span>PaginatedResourceWrapper</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/PaginatedResourceWrapper.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/oauth/passwordflow.js~passwordflow",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html",
    "<span>PasswordFlow</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/oauth/PasswordFlow.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/permission.js~permission",
    "class/src/crud/Permission.js~Permission.html",
    "<span>Permission</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Permission.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/placename.js~placename",
    "class/src/crud/PlaceName.js~PlaceName.html",
    "<span>PlaceName</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/PlaceName.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/base/resourcebase.js~resourcebase",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html",
    "<span>ResourceBase</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/base/ResourceBase.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/resourcecache.js~resourcecache",
    "class/src/ResourceCache.js~ResourceCache.html",
    "<span>ResourceCache</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/ResourceCache.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/resourceproxy.js~resourceproxy",
    "class/src/ResourceProxy.js~ResourceProxy.html",
    "<span>ResourceProxy</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/ResourceProxy.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/utils/singleton.js~singleton",
    "class/src/utils/Singleton.js~Singleton.html",
    "<span>Singleton</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/utils/Singleton.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/utils/staticclass.js~staticclass",
    "class/src/utils/StaticClass.js~StaticClass.html",
    "<span>StaticClass</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/utils/StaticClass.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/staticclasserror.js~staticclasserror",
    "class/src/errors/StaticClassError.js~StaticClassError.html",
    "<span>StaticClassError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/StaticClassError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/svg.js~svg",
    "class/src/crud/Svg.js~Svg.html",
    "<span>Svg</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/Svg.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/svgset.js~svgset",
    "class/src/crud/SvgSet.js~SvgSet.html",
    "<span>SvgSet</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/SvgSet.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/svgsettype.js~svgsettype",
    "class/src/crud/SvgSetType.js~SvgSetType.html",
    "<span>SvgSetType</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/SvgSetType.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/traits/trait.js~trait",
    "class/src/traits/Trait.js~Trait.html",
    "<span>Trait</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/traits/Trait.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/unsupportedcruderror.js~unsupportedcruderror",
    "class/src/errors/UnsupportedCrudError.js~UnsupportedCrudError.html",
    "<span>UnsupportedCrudError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/UnsupportedCrudError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/crud/user.js~user",
    "class/src/crud/User.js~User.html",
    "<span>User</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/crud/User.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/errors/validationerror.js~validationerror",
    "class/src/errors/ValidationError.js~ValidationError.html",
    "<span>ValidationError</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/errors/ValidationError.js</span>",
    "class"
  ],
  [
    "@mapcreator/maps4news/src/utils/requests.js~encodequerystring",
    "function/index.html#static-function-encodeQueryString",
    "<span>encodeQueryString</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/utils/requests.js</span>",
    "function"
  ],
  [
    "@mapcreator/maps4news/src/utils/helpers.js~getpaginatedrange",
    "function/index.html#static-function-getPaginatedRange",
    "<span>getPaginatedRange</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "@mapcreator/maps4news/src/utils/requests.js~makerequest",
    "function/index.html#static-function-makeRequest",
    "<span>makeRequest</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/utils/requests.js</span>",
    "function"
  ],
  [
    "@mapcreator/maps4news/src/utils/helpers.js~paginateresource",
    "function/index.html#static-function-paginateResource",
    "<span>paginateResource</span> <span class=\"search-result-import-path\">@mapcreator/maps4news/src/utils/helpers.js</span>",
    "function"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "BuiltinExternal/ECMAScriptExternal.js~Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "BuiltinExternal/ECMAScriptExternal.js~ArrayBuffer",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~Boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "BuiltinExternal/ECMAScriptExternal.js~DataView",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "BuiltinExternal/ECMAScriptExternal.js~Date",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "BuiltinExternal/ECMAScriptExternal.js~Error",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "BuiltinExternal/ECMAScriptExternal.js~EvalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "BuiltinExternal/ECMAScriptExternal.js~Float64Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~Function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "BuiltinExternal/ECMAScriptExternal.js~Generator",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "BuiltinExternal/ECMAScriptExternal.js~GeneratorFunction",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "BuiltinExternal/ECMAScriptExternal.js~Infinity",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Int8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "BuiltinExternal/ECMAScriptExternal.js~InternalError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "BuiltinExternal/ECMAScriptExternal.js~JSON",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "BuiltinExternal/ECMAScriptExternal.js~Map",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "BuiltinExternal/ECMAScriptExternal.js~NaN",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~Number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~Object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "BuiltinExternal/ECMAScriptExternal.js~Promise",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "BuiltinExternal/ECMAScriptExternal.js~Proxy",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "BuiltinExternal/ECMAScriptExternal.js~RangeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "BuiltinExternal/ECMAScriptExternal.js~ReferenceError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "BuiltinExternal/ECMAScriptExternal.js~Reflect",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "BuiltinExternal/ECMAScriptExternal.js~RegExp",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "BuiltinExternal/ECMAScriptExternal.js~Set",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~String",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "BuiltinExternal/ECMAScriptExternal.js~Symbol",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "BuiltinExternal/ECMAScriptExternal.js~SyntaxError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "BuiltinExternal/ECMAScriptExternal.js~TypeError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "BuiltinExternal/ECMAScriptExternal.js~URIError",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint16Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint32Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8Array",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "BuiltinExternal/ECMAScriptExternal.js~Uint8ClampedArray",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "BuiltinExternal/ECMAScriptExternal.js~WeakMap",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "BuiltinExternal/ECMAScriptExternal.js~WeakSet",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "BuiltinExternal/ECMAScriptExternal.js~boolean",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "BuiltinExternal/ECMAScriptExternal.js~function",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "BuiltinExternal/ECMAScriptExternal.js~null",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "BuiltinExternal/ECMAScriptExternal.js~number",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "BuiltinExternal/ECMAScriptExternal.js~object",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "BuiltinExternal/ECMAScriptExternal.js~string",
    "external"
  ],
  [
    "builtinexternal/ecmascriptexternal.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "BuiltinExternal/ECMAScriptExternal.js~undefined",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~audiocontext",
    "https://developer.mozilla.org/en/docs/Web/API/AudioContext",
    "BuiltinExternal/WebAPIExternal.js~AudioContext",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~canvasrenderingcontext2d",
    "https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D",
    "BuiltinExternal/WebAPIExternal.js~CanvasRenderingContext2D",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~documentfragment",
    "https://developer.mozilla.org/en-US/docs/Web/API/DocumentFragment",
    "BuiltinExternal/WebAPIExternal.js~DocumentFragment",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~element",
    "https://developer.mozilla.org/en-US/docs/Web/API/Element",
    "BuiltinExternal/WebAPIExternal.js~Element",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~event",
    "https://developer.mozilla.org/en-US/docs/Web/API/Event",
    "BuiltinExternal/WebAPIExternal.js~Event",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~node",
    "https://developer.mozilla.org/en-US/docs/Web/API/Node",
    "BuiltinExternal/WebAPIExternal.js~Node",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~nodelist",
    "https://developer.mozilla.org/en-US/docs/Web/API/NodeList",
    "BuiltinExternal/WebAPIExternal.js~NodeList",
    "external"
  ],
  [
    "builtinexternal/webapiexternal.js~xmlhttprequest",
    "https://developer.mozilla.org/en/docs/Web/API/XMLHttpRequest",
    "BuiltinExternal/WebAPIExternal.js~XMLHttpRequest",
    "external"
  ],
  [
    "src/imagehandler.js",
    "file/src/ImageHandler.js.html",
    "src/ImageHandler.js",
    "file"
  ],
  [
    "src/imagehandler.js~imagehandler#api",
    "class/src/ImageHandler.js~ImageHandler.html#instance-get-api",
    "src/ImageHandler.js~ImageHandler#api",
    "member"
  ],
  [
    "src/imagehandler.js~imagehandler#constructor",
    "class/src/ImageHandler.js~ImageHandler.html#instance-constructor-constructor",
    "src/ImageHandler.js~ImageHandler#constructor",
    "method"
  ],
  [
    "src/imagehandler.js~imagehandler#delete",
    "class/src/ImageHandler.js~ImageHandler.html#instance-method-delete",
    "src/ImageHandler.js~ImageHandler#delete",
    "method"
  ],
  [
    "src/imagehandler.js~imagehandler#download",
    "class/src/ImageHandler.js~ImageHandler.html#instance-method-download",
    "src/ImageHandler.js~ImageHandler#download",
    "method"
  ],
  [
    "src/imagehandler.js~imagehandler#upload",
    "class/src/ImageHandler.js~ImageHandler.html#instance-method-upload",
    "src/ImageHandler.js~ImageHandler#upload",
    "method"
  ],
  [
    "src/imagehandler.js~imagehandler#url",
    "class/src/ImageHandler.js~ImageHandler.html#instance-get-url",
    "src/ImageHandler.js~ImageHandler#url",
    "member"
  ],
  [
    "src/maps4news.js",
    "file/src/Maps4News.js.html",
    "src/Maps4News.js",
    "file"
  ],
  [
    "src/maps4news.js~maps4news#auth",
    "class/src/Maps4News.js~Maps4News.html#instance-set-auth",
    "src/Maps4News.js~Maps4News#auth",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#auth",
    "class/src/Maps4News.js~Maps4News.html#instance-get-auth",
    "src/Maps4News.js~Maps4News#auth",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#authenticate",
    "class/src/Maps4News.js~Maps4News.html#instance-method-authenticate",
    "src/Maps4News.js~Maps4News#authenticate",
    "method"
  ],
  [
    "src/maps4news.js~maps4news#authenticated",
    "class/src/Maps4News.js~Maps4News.html#instance-get-authenticated",
    "src/Maps4News.js~Maps4News#authenticated",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#cache",
    "class/src/Maps4News.js~Maps4News.html#instance-get-cache",
    "src/Maps4News.js~Maps4News#cache",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#choropleths",
    "class/src/Maps4News.js~Maps4News.html#instance-get-choropleths",
    "src/Maps4News.js~Maps4News#choropleths",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#colors",
    "class/src/Maps4News.js~Maps4News.html#instance-get-colors",
    "src/Maps4News.js~Maps4News#colors",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#constructor",
    "class/src/Maps4News.js~Maps4News.html#instance-constructor-constructor",
    "src/Maps4News.js~Maps4News#constructor",
    "method"
  ],
  [
    "src/maps4news.js~maps4news#contracts",
    "class/src/Maps4News.js~Maps4News.html#instance-get-contracts",
    "src/Maps4News.js~Maps4News#contracts",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#defaults",
    "class/src/Maps4News.js~Maps4News.html#instance-member-defaults",
    "src/Maps4News.js~Maps4News#defaults",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#dimensionsets",
    "class/src/Maps4News.js~Maps4News.html#instance-get-dimensionSets",
    "src/Maps4News.js~Maps4News#dimensionSets",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#dimensions",
    "class/src/Maps4News.js~Maps4News.html#instance-get-dimensions",
    "src/Maps4News.js~Maps4News#dimensions",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#faqs",
    "class/src/Maps4News.js~Maps4News.html#instance-get-faqs",
    "src/Maps4News.js~Maps4News#faqs",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#features",
    "class/src/Maps4News.js~Maps4News.html#instance-get-features",
    "src/Maps4News.js~Maps4News#features",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#fontfamilies",
    "class/src/Maps4News.js~Maps4News.html#instance-get-fontFamilies",
    "src/Maps4News.js~Maps4News#fontFamilies",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#fonts",
    "class/src/Maps4News.js~Maps4News.html#instance-get-fonts",
    "src/Maps4News.js~Maps4News#fonts",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#highlights",
    "class/src/Maps4News.js~Maps4News.html#instance-get-highlights",
    "src/Maps4News.js~Maps4News#highlights",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#host",
    "class/src/Maps4News.js~Maps4News.html#instance-set-host",
    "src/Maps4News.js~Maps4News#host",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#host",
    "class/src/Maps4News.js~Maps4News.html#instance-get-host",
    "src/Maps4News.js~Maps4News#host",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#insetmaps",
    "class/src/Maps4News.js~Maps4News.html#instance-get-insetMaps",
    "src/Maps4News.js~Maps4News#insetMaps",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#jobshares",
    "class/src/Maps4News.js~Maps4News.html#instance-get-jobShares",
    "src/Maps4News.js~Maps4News#jobShares",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#jobtypes",
    "class/src/Maps4News.js~Maps4News.html#instance-get-jobTypes",
    "src/Maps4News.js~Maps4News#jobTypes",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#jobs",
    "class/src/Maps4News.js~Maps4News.html#instance-get-jobs",
    "src/Maps4News.js~Maps4News#jobs",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#languages",
    "class/src/Maps4News.js~Maps4News.html#instance-get-languages",
    "src/Maps4News.js~Maps4News#languages",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#layers",
    "class/src/Maps4News.js~Maps4News.html#instance-get-layers",
    "src/Maps4News.js~Maps4News#layers",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#logout",
    "class/src/Maps4News.js~Maps4News.html#instance-method-logout",
    "src/Maps4News.js~Maps4News#logout",
    "method"
  ],
  [
    "src/maps4news.js~maps4news#mapstylesets",
    "class/src/Maps4News.js~Maps4News.html#instance-get-mapstyleSets",
    "src/Maps4News.js~Maps4News#mapstyleSets",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#mapstyles",
    "class/src/Maps4News.js~Maps4News.html#instance-get-mapstyles",
    "src/Maps4News.js~Maps4News#mapstyles",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#notifications",
    "class/src/Maps4News.js~Maps4News.html#instance-get-notifications",
    "src/Maps4News.js~Maps4News#notifications",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#organisations",
    "class/src/Maps4News.js~Maps4News.html#instance-get-organisations",
    "src/Maps4News.js~Maps4News#organisations",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#permissions",
    "class/src/Maps4News.js~Maps4News.html#instance-get-permissions",
    "src/Maps4News.js~Maps4News#permissions",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#placenames",
    "class/src/Maps4News.js~Maps4News.html#instance-get-placeNames",
    "src/Maps4News.js~Maps4News#placeNames",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#request",
    "class/src/Maps4News.js~Maps4News.html#instance-method-request",
    "src/Maps4News.js~Maps4News#request",
    "method"
  ],
  [
    "src/maps4news.js~maps4news#static",
    "class/src/Maps4News.js~Maps4News.html#instance-method-static",
    "src/Maps4News.js~Maps4News#static",
    "method"
  ],
  [
    "src/maps4news.js~maps4news#svgsettypes",
    "class/src/Maps4News.js~Maps4News.html#instance-get-svgSetTypes",
    "src/Maps4News.js~Maps4News#svgSetTypes",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#svgsets",
    "class/src/Maps4News.js~Maps4News.html#instance-get-svgSets",
    "src/Maps4News.js~Maps4News#svgSets",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#svgs",
    "class/src/Maps4News.js~Maps4News.html#instance-get-svgs",
    "src/Maps4News.js~Maps4News#svgs",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#testxhr",
    "class/src/Maps4News.js~Maps4News.html#instance-method-testXhr",
    "src/Maps4News.js~Maps4News#testXhr",
    "method"
  ],
  [
    "src/maps4news.js~maps4news#users",
    "class/src/Maps4News.js~Maps4News.html#instance-get-users",
    "src/Maps4News.js~Maps4News#users",
    "member"
  ],
  [
    "src/maps4news.js~maps4news#version",
    "class/src/Maps4News.js~Maps4News.html#instance-get-version",
    "src/Maps4News.js~Maps4News#version",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js",
    "file/src/PaginatedResourceListing.js.html",
    "src/PaginatedResourceListing.js",
    "file"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#target",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-Target",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#Target",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#api",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-api",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#api",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#cachetoken",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-cacheToken",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#cacheToken",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#data",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-data",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#data",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#getpage",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-method-getPage",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#getPage",
    "method"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#hasnext",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-hasNext",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#hasNext",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#hasprevious",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-hasPrevious",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#hasPrevious",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#next",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-method-next",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#next",
    "method"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#page",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-page",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#page",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#pagecount",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-pageCount",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#pageCount",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#perpage",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-perPage",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#perPage",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#previous",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-method-previous",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#previous",
    "method"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#query",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-set-query",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#query",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#query",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-query",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#query",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#route",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-route",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#route",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#rows",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-get-rows",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#rows",
    "member"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting#wrap",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#instance-method-wrap",
    "src/PaginatedResourceListing.js~PaginatedResourceListing#wrap",
    "method"
  ],
  [
    "src/paginatedresourcelisting.js~paginatedresourcelisting.headerprefix",
    "class/src/PaginatedResourceListing.js~PaginatedResourceListing.html#static-get-headerPrefix",
    "src/PaginatedResourceListing.js~PaginatedResourceListing.headerPrefix",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js",
    "file/src/PaginatedResourceWrapper.js.html",
    "src/PaginatedResourceWrapper.js",
    "file"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#api",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-api",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#api",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#cache",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-cache",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#cache",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#cacheenabled",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-member-cacheEnabled",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#cacheEnabled",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#cachetime",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-member-cacheTime",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#cacheTime",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#constructor",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-constructor-constructor",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#constructor",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#currentpage",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-set-currentPage",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#currentPage",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#currentpage",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-currentPage",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#currentPage",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#data",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-member-data",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#data",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#get",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-get",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#get",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#hasnext",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-hasNext",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#hasNext",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#hasprevious",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-hasPrevious",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#hasPrevious",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#inflight",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-inflight",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#inflight",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#next",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-next",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#next",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#off",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-off",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#off",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#on",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-on",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#on",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#pagecount",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-pageCount",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#pageCount",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#path",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-path",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#path",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#previous",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-previous",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#previous",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#query",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-set-query",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#query",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#query",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-query",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#query",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#rebuild",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-rebuild",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#rebuild",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#refresh",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-method-refresh",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#refresh",
    "method"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#sharecache",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-shareCache",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#shareCache",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#sharecache",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-set-shareCache",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#shareCache",
    "member"
  ],
  [
    "src/paginatedresourcewrapper.js~paginatedresourcewrapper#waiting",
    "class/src/PaginatedResourceWrapper.js~PaginatedResourceWrapper.html#instance-get-waiting",
    "src/PaginatedResourceWrapper.js~PaginatedResourceWrapper#waiting",
    "member"
  ],
  [
    "src/resourcecache.js",
    "file/src/ResourceCache.js.html",
    "src/ResourceCache.js",
    "file"
  ],
  [
    "src/resourcecache.js~resourcecache#cachetime",
    "class/src/ResourceCache.js~ResourceCache.html#instance-member-cacheTime",
    "src/ResourceCache.js~ResourceCache#cacheTime",
    "member"
  ],
  [
    "src/resourcecache.js~resourcecache#clear",
    "class/src/ResourceCache.js~ResourceCache.html#instance-method-clear",
    "src/ResourceCache.js~ResourceCache#clear",
    "method"
  ],
  [
    "src/resourcecache.js~resourcecache#collectpages",
    "class/src/ResourceCache.js~ResourceCache.html#instance-method-collectPages",
    "src/ResourceCache.js~ResourceCache#collectPages",
    "method"
  ],
  [
    "src/resourcecache.js~resourcecache#constructor",
    "class/src/ResourceCache.js~ResourceCache.html#instance-constructor-constructor",
    "src/ResourceCache.js~ResourceCache#constructor",
    "method"
  ],
  [
    "src/resourcecache.js~resourcecache#emitter",
    "class/src/ResourceCache.js~ResourceCache.html#instance-member-emitter",
    "src/ResourceCache.js~ResourceCache#emitter",
    "member"
  ],
  [
    "src/resourcecache.js~resourcecache#push",
    "class/src/ResourceCache.js~ResourceCache.html#instance-method-push",
    "src/ResourceCache.js~ResourceCache#push",
    "method"
  ],
  [
    "src/resourcecache.js~resourcecache#resolve",
    "class/src/ResourceCache.js~ResourceCache.html#instance-method-resolve",
    "src/ResourceCache.js~ResourceCache#resolve",
    "method"
  ],
  [
    "src/resourcecache.js~resourcecache#revalidate",
    "class/src/ResourceCache.js~ResourceCache.html#instance-method-revalidate",
    "src/ResourceCache.js~ResourceCache#revalidate",
    "method"
  ],
  [
    "src/resourceproxy.js",
    "file/src/ResourceProxy.js.html",
    "src/ResourceProxy.js",
    "file"
  ],
  [
    "src/resourceproxy.js~resourceproxy#target",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-get-Target",
    "src/ResourceProxy.js~ResourceProxy#Target",
    "member"
  ],
  [
    "src/resourceproxy.js~resourceproxy#accessorname",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-get-accessorName",
    "src/ResourceProxy.js~ResourceProxy#accessorName",
    "member"
  ],
  [
    "src/resourceproxy.js~resourceproxy#api",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-get-api",
    "src/ResourceProxy.js~ResourceProxy#api",
    "member"
  ],
  [
    "src/resourceproxy.js~resourceproxy#constructor",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-constructor-constructor",
    "src/ResourceProxy.js~ResourceProxy#constructor",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#get",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-get",
    "src/ResourceProxy.js~ResourceProxy#get",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#list",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-list",
    "src/ResourceProxy.js~ResourceProxy#list",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#listandwrap",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-listAndWrap",
    "src/ResourceProxy.js~ResourceProxy#listAndWrap",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#new",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-new",
    "src/ResourceProxy.js~ResourceProxy#new",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#search",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-search",
    "src/ResourceProxy.js~ResourceProxy#search",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#searchandwrap",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-searchAndWrap",
    "src/ResourceProxy.js~ResourceProxy#searchAndWrap",
    "method"
  ],
  [
    "src/resourceproxy.js~resourceproxy#select",
    "class/src/ResourceProxy.js~ResourceProxy.html#instance-method-select",
    "src/ResourceProxy.js~ResourceProxy#select",
    "method"
  ],
  [
    "src/crud/choropleth.js",
    "file/src/crud/Choropleth.js.html",
    "src/crud/Choropleth.js",
    "file"
  ],
  [
    "src/crud/choropleth.js~choropleth#resourcename",
    "class/src/crud/Choropleth.js~Choropleth.html#instance-get-resourceName",
    "src/crud/Choropleth.js~Choropleth#resourceName",
    "member"
  ],
  [
    "src/crud/color.js",
    "file/src/crud/Color.js.html",
    "src/crud/Color.js",
    "file"
  ],
  [
    "src/crud/color.js~color#resourcename",
    "class/src/crud/Color.js~Color.html#instance-get-resourceName",
    "src/crud/Color.js~Color#resourceName",
    "member"
  ],
  [
    "src/crud/contract.js",
    "file/src/crud/Contract.js.html",
    "src/crud/Contract.js",
    "file"
  ],
  [
    "src/crud/contract.js~contract#resourcename",
    "class/src/crud/Contract.js~Contract.html#instance-get-resourceName",
    "src/crud/Contract.js~Contract#resourceName",
    "member"
  ],
  [
    "src/crud/dimension.js",
    "file/src/crud/Dimension.js.html",
    "src/crud/Dimension.js",
    "file"
  ],
  [
    "src/crud/dimension.js~dimension#resourcename",
    "class/src/crud/Dimension.js~Dimension.html#instance-get-resourceName",
    "src/crud/Dimension.js~Dimension#resourceName",
    "member"
  ],
  [
    "src/crud/dimensionset.js",
    "file/src/crud/DimensionSet.js.html",
    "src/crud/DimensionSet.js",
    "file"
  ],
  [
    "src/crud/dimensionset.js~dimensionset#resourcename",
    "class/src/crud/DimensionSet.js~DimensionSet.html#instance-get-resourceName",
    "src/crud/DimensionSet.js~DimensionSet#resourceName",
    "member"
  ],
  [
    "src/crud/dimensionset.js~dimensionset#resourcepath",
    "class/src/crud/DimensionSet.js~DimensionSet.html#instance-get-resourcePath",
    "src/crud/DimensionSet.js~DimensionSet#resourcePath",
    "member"
  ],
  [
    "src/crud/faq.js",
    "file/src/crud/Faq.js.html",
    "src/crud/Faq.js",
    "file"
  ],
  [
    "src/crud/faq.js~faq#resourcename",
    "class/src/crud/Faq.js~Faq.html#instance-get-resourceName",
    "src/crud/Faq.js~Faq#resourceName",
    "member"
  ],
  [
    "src/crud/feature.js",
    "file/src/crud/Feature.js.html",
    "src/crud/Feature.js",
    "file"
  ],
  [
    "src/crud/feature.js~feature#resourcename",
    "class/src/crud/Feature.js~Feature.html#instance-get-resourceName",
    "src/crud/Feature.js~Feature#resourceName",
    "member"
  ],
  [
    "src/crud/font.js",
    "file/src/crud/Font.js.html",
    "src/crud/Font.js",
    "file"
  ],
  [
    "src/crud/font.js~font#resourcename",
    "class/src/crud/Font.js~Font.html#instance-get-resourceName",
    "src/crud/Font.js~Font#resourceName",
    "member"
  ],
  [
    "src/crud/fontfamily.js",
    "file/src/crud/FontFamily.js.html",
    "src/crud/FontFamily.js",
    "file"
  ],
  [
    "src/crud/fontfamily.js~fontfamily#resourcename",
    "class/src/crud/FontFamily.js~FontFamily.html#instance-get-resourceName",
    "src/crud/FontFamily.js~FontFamily#resourceName",
    "member"
  ],
  [
    "src/crud/fontfamily.js~fontfamily#resourcepath",
    "class/src/crud/FontFamily.js~FontFamily.html#instance-get-resourcePath",
    "src/crud/FontFamily.js~FontFamily#resourcePath",
    "member"
  ],
  [
    "src/crud/highlight.js",
    "file/src/crud/Highlight.js.html",
    "src/crud/Highlight.js",
    "file"
  ],
  [
    "src/crud/highlight.js~highlight#resourcename",
    "class/src/crud/Highlight.js~Highlight.html#instance-get-resourceName",
    "src/crud/Highlight.js~Highlight#resourceName",
    "member"
  ],
  [
    "src/crud/insetmap.js",
    "file/src/crud/InsetMap.js.html",
    "src/crud/InsetMap.js",
    "file"
  ],
  [
    "src/crud/insetmap.js~insetmap#resourcename",
    "class/src/crud/InsetMap.js~InsetMap.html#instance-get-resourceName",
    "src/crud/InsetMap.js~InsetMap#resourceName",
    "member"
  ],
  [
    "src/crud/job.js",
    "file/src/crud/Job.js.html",
    "src/crud/Job.js",
    "file"
  ],
  [
    "src/crud/job.js~job#getrevision",
    "class/src/crud/Job.js~Job.html#instance-method-getRevision",
    "src/crud/Job.js~Job#getRevision",
    "method"
  ],
  [
    "src/crud/job.js~job#lastarchiveurl",
    "class/src/crud/Job.js~Job.html#instance-get-lastArchiveUrl",
    "src/crud/Job.js~Job#lastArchiveUrl",
    "member"
  ],
  [
    "src/crud/job.js~job#lastpreviewurl",
    "class/src/crud/Job.js~Job.html#instance-get-lastPreviewUrl",
    "src/crud/Job.js~Job#lastPreviewUrl",
    "member"
  ],
  [
    "src/crud/job.js~job#resourcename",
    "class/src/crud/Job.js~Job.html#instance-get-resourceName",
    "src/crud/Job.js~Job#resourceName",
    "member"
  ],
  [
    "src/crud/job.js~job#results",
    "class/src/crud/Job.js~Job.html#instance-method-results",
    "src/crud/Job.js~Job#results",
    "method"
  ],
  [
    "src/crud/job.js~job#revisions",
    "class/src/crud/Job.js~Job.html#instance-method-revisions",
    "src/crud/Job.js~Job#revisions",
    "method"
  ],
  [
    "src/crud/jobresult.js",
    "file/src/crud/JobResult.js.html",
    "src/crud/JobResult.js",
    "file"
  ],
  [
    "src/crud/jobresult.js~jobresult#archiveurl",
    "class/src/crud/JobResult.js~JobResult.html#instance-get-archiveUrl",
    "src/crud/JobResult.js~JobResult#archiveUrl",
    "member"
  ],
  [
    "src/crud/jobresult.js~jobresult#previewurl",
    "class/src/crud/JobResult.js~JobResult.html#instance-get-previewUrl",
    "src/crud/JobResult.js~JobResult#previewUrl",
    "member"
  ],
  [
    "src/crud/jobresult.js~jobresult#resourcename",
    "class/src/crud/JobResult.js~JobResult.html#instance-get-resourceName",
    "src/crud/JobResult.js~JobResult#resourceName",
    "member"
  ],
  [
    "src/crud/jobrevision.js",
    "file/src/crud/JobRevision.js.html",
    "src/crud/JobRevision.js",
    "file"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#baseurl",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-get-baseUrl",
    "src/crud/JobRevision.js~JobRevision#baseUrl",
    "member"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#build",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-build",
    "src/crud/JobRevision.js~JobRevision#build",
    "method"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#cancel",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-cancel",
    "src/crud/JobRevision.js~JobRevision#cancel",
    "method"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#layers",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-layers",
    "src/crud/JobRevision.js~JobRevision#layers",
    "method"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#object",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-object",
    "src/crud/JobRevision.js~JobRevision#object",
    "method"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#resourcename",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-get-resourceName",
    "src/crud/JobRevision.js~JobRevision#resourceName",
    "member"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#resourcepath",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-get-resourcePath",
    "src/crud/JobRevision.js~JobRevision#resourcePath",
    "member"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#result",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-result",
    "src/crud/JobRevision.js~JobRevision#result",
    "method"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#save",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-save",
    "src/crud/JobRevision.js~JobRevision#save",
    "method"
  ],
  [
    "src/crud/jobrevision.js~jobrevision#share",
    "class/src/crud/JobRevision.js~JobRevision.html#instance-method-share",
    "src/crud/JobRevision.js~JobRevision#share",
    "method"
  ],
  [
    "src/crud/jobshare.js",
    "file/src/crud/JobShare.js.html",
    "src/crud/JobShare.js",
    "file"
  ],
  [
    "src/crud/jobshare.js~jobshare#resourcename",
    "class/src/crud/JobShare.js~JobShare.html#instance-get-resourceName",
    "src/crud/JobShare.js~JobShare#resourceName",
    "member"
  ],
  [
    "src/crud/jobshare.js~jobshare#resourcepath",
    "class/src/crud/JobShare.js~JobShare.html#instance-get-resourcePath",
    "src/crud/JobShare.js~JobShare#resourcePath",
    "member"
  ],
  [
    "src/crud/jobshare.js~jobshare.visibility",
    "class/src/crud/JobShare.js~JobShare.html#static-get-visibility",
    "src/crud/JobShare.js~JobShare.visibility",
    "member"
  ],
  [
    "src/crud/jobtype.js",
    "file/src/crud/JobType.js.html",
    "src/crud/JobType.js",
    "file"
  ],
  [
    "src/crud/jobtype.js~jobtype#resourcename",
    "class/src/crud/JobType.js~JobType.html#instance-get-resourceName",
    "src/crud/JobType.js~JobType#resourceName",
    "member"
  ],
  [
    "src/crud/jobtype.js~jobtype#resourcepath",
    "class/src/crud/JobType.js~JobType.html#instance-get-resourcePath",
    "src/crud/JobType.js~JobType#resourcePath",
    "member"
  ],
  [
    "src/crud/language.js",
    "file/src/crud/Language.js.html",
    "src/crud/Language.js",
    "file"
  ],
  [
    "src/crud/language.js~language#resourcename",
    "class/src/crud/Language.js~Language.html#instance-get-resourceName",
    "src/crud/Language.js~Language#resourceName",
    "member"
  ],
  [
    "src/crud/language.js~language#tostring",
    "class/src/crud/Language.js~Language.html#instance-method-toString",
    "src/crud/Language.js~Language#toString",
    "method"
  ],
  [
    "src/crud/layer.js",
    "file/src/crud/Layer.js.html",
    "src/crud/Layer.js",
    "file"
  ],
  [
    "src/crud/layer.js~layer#resourcename",
    "class/src/crud/Layer.js~Layer.html#instance-get-resourceName",
    "src/crud/Layer.js~Layer#resourceName",
    "member"
  ],
  [
    "src/crud/mapstyle.js",
    "file/src/crud/Mapstyle.js.html",
    "src/crud/Mapstyle.js",
    "file"
  ],
  [
    "src/crud/mapstyle.js~mapstyle#resourcename",
    "class/src/crud/Mapstyle.js~Mapstyle.html#instance-get-resourceName",
    "src/crud/Mapstyle.js~Mapstyle#resourceName",
    "member"
  ],
  [
    "src/crud/mapstyleset.js",
    "file/src/crud/MapstyleSet.js.html",
    "src/crud/MapstyleSet.js",
    "file"
  ],
  [
    "src/crud/mapstyleset.js~mapstyleset#resourcename",
    "class/src/crud/MapstyleSet.js~MapstyleSet.html#instance-get-resourceName",
    "src/crud/MapstyleSet.js~MapstyleSet#resourceName",
    "member"
  ],
  [
    "src/crud/mapstyleset.js~mapstyleset#resourcepath",
    "class/src/crud/MapstyleSet.js~MapstyleSet.html#instance-get-resourcePath",
    "src/crud/MapstyleSet.js~MapstyleSet#resourcePath",
    "member"
  ],
  [
    "src/crud/notification.js",
    "file/src/crud/Notification.js.html",
    "src/crud/Notification.js",
    "file"
  ],
  [
    "src/crud/notification.js~notification#resourcename",
    "class/src/crud/Notification.js~Notification.html#instance-get-resourceName",
    "src/crud/Notification.js~Notification#resourceName",
    "member"
  ],
  [
    "src/crud/organisation.js",
    "file/src/crud/Organisation.js.html",
    "src/crud/Organisation.js",
    "file"
  ],
  [
    "src/crud/organisation.js~organisation#attach",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-attach",
    "src/crud/Organisation.js~Organisation#attach",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#colors",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-colors",
    "src/crud/Organisation.js~Organisation#colors",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#contracts",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-contracts",
    "src/crud/Organisation.js~Organisation#contracts",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#dimensionsets",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-dimensionSets",
    "src/crud/Organisation.js~Organisation#dimensionSets",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#features",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-features",
    "src/crud/Organisation.js~Organisation#features",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#fontfamilies",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-fontFamilies",
    "src/crud/Organisation.js~Organisation#fontFamilies",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#jobshares",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-jobShares",
    "src/crud/Organisation.js~Organisation#jobShares",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#jobtypes",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-jobTypes",
    "src/crud/Organisation.js~Organisation#jobTypes",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#layers",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-layers",
    "src/crud/Organisation.js~Organisation#layers",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#mapstylesets",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-mapstyleSets",
    "src/crud/Organisation.js~Organisation#mapstyleSets",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#resourcename",
    "class/src/crud/Organisation.js~Organisation.html#instance-get-resourceName",
    "src/crud/Organisation.js~Organisation#resourceName",
    "member"
  ],
  [
    "src/crud/organisation.js~organisation#svgsets",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-svgSets",
    "src/crud/Organisation.js~Organisation#svgSets",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#sync",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-sync",
    "src/crud/Organisation.js~Organisation#sync",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#unlink",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-unlink",
    "src/crud/Organisation.js~Organisation#unlink",
    "method"
  ],
  [
    "src/crud/organisation.js~organisation#users",
    "class/src/crud/Organisation.js~Organisation.html#instance-method-users",
    "src/crud/Organisation.js~Organisation#users",
    "method"
  ],
  [
    "src/crud/permission.js",
    "file/src/crud/Permission.js.html",
    "src/crud/Permission.js",
    "file"
  ],
  [
    "src/crud/permission.js~permission#resourcename",
    "class/src/crud/Permission.js~Permission.html#instance-get-resourceName",
    "src/crud/Permission.js~Permission#resourceName",
    "member"
  ],
  [
    "src/crud/placename.js",
    "file/src/crud/PlaceName.js.html",
    "src/crud/PlaceName.js",
    "file"
  ],
  [
    "src/crud/placename.js~placename#resourcename",
    "class/src/crud/PlaceName.js~PlaceName.html#instance-get-resourceName",
    "src/crud/PlaceName.js~PlaceName#resourceName",
    "member"
  ],
  [
    "src/crud/svg.js",
    "file/src/crud/Svg.js.html",
    "src/crud/Svg.js",
    "file"
  ],
  [
    "src/crud/svg.js~svg#resourcename",
    "class/src/crud/Svg.js~Svg.html#instance-get-resourceName",
    "src/crud/Svg.js~Svg#resourceName",
    "member"
  ],
  [
    "src/crud/svgset.js",
    "file/src/crud/SvgSet.js.html",
    "src/crud/SvgSet.js",
    "file"
  ],
  [
    "src/crud/svgset.js~svgset#resourcename",
    "class/src/crud/SvgSet.js~SvgSet.html#instance-get-resourceName",
    "src/crud/SvgSet.js~SvgSet#resourceName",
    "member"
  ],
  [
    "src/crud/svgset.js~svgset#resourcepath",
    "class/src/crud/SvgSet.js~SvgSet.html#instance-get-resourcePath",
    "src/crud/SvgSet.js~SvgSet#resourcePath",
    "member"
  ],
  [
    "src/crud/svgsettype.js",
    "file/src/crud/SvgSetType.js.html",
    "src/crud/SvgSetType.js",
    "file"
  ],
  [
    "src/crud/svgsettype.js~svgsettype#resourcename",
    "class/src/crud/SvgSetType.js~SvgSetType.html#instance-get-resourceName",
    "src/crud/SvgSetType.js~SvgSetType#resourceName",
    "member"
  ],
  [
    "src/crud/svgsettype.js~svgsettype#resourcepath",
    "class/src/crud/SvgSetType.js~SvgSetType.html#instance-get-resourcePath",
    "src/crud/SvgSetType.js~SvgSetType#resourcePath",
    "member"
  ],
  [
    "src/crud/user.js",
    "file/src/crud/User.js.html",
    "src/crud/User.js",
    "file"
  ],
  [
    "src/crud/user.js~user#colors",
    "class/src/crud/User.js~User.html#instance-method-colors",
    "src/crud/User.js~User#colors",
    "method"
  ],
  [
    "src/crud/user.js~user#dimensionsets",
    "class/src/crud/User.js~User.html#instance-method-dimensionSets",
    "src/crud/User.js~User#dimensionSets",
    "method"
  ],
  [
    "src/crud/user.js~user#features",
    "class/src/crud/User.js~User.html#instance-method-features",
    "src/crud/User.js~User#features",
    "method"
  ],
  [
    "src/crud/user.js~user#fontfamilies",
    "class/src/crud/User.js~User.html#instance-method-fontFamilies",
    "src/crud/User.js~User#fontFamilies",
    "method"
  ],
  [
    "src/crud/user.js~user#ips",
    "class/src/crud/User.js~User.html#instance-method-ips",
    "src/crud/User.js~User#ips",
    "method"
  ],
  [
    "src/crud/user.js~user#isadmin",
    "class/src/crud/User.js~User.html#instance-method-isAdmin",
    "src/crud/User.js~User#isAdmin",
    "method"
  ],
  [
    "src/crud/user.js~user#jobshares",
    "class/src/crud/User.js~User.html#instance-method-jobShares",
    "src/crud/User.js~User#jobShares",
    "method"
  ],
  [
    "src/crud/user.js~user#jobtypes",
    "class/src/crud/User.js~User.html#instance-method-jobTypes",
    "src/crud/User.js~User#jobTypes",
    "method"
  ],
  [
    "src/crud/user.js~user#jobs",
    "class/src/crud/User.js~User.html#instance-method-jobs",
    "src/crud/User.js~User#jobs",
    "method"
  ],
  [
    "src/crud/user.js~user#language",
    "class/src/crud/User.js~User.html#instance-method-language",
    "src/crud/User.js~User#language",
    "method"
  ],
  [
    "src/crud/user.js~user#layers",
    "class/src/crud/User.js~User.html#instance-method-layers",
    "src/crud/User.js~User#layers",
    "method"
  ],
  [
    "src/crud/user.js~user#mapstylesets",
    "class/src/crud/User.js~User.html#instance-method-mapstyleSets",
    "src/crud/User.js~User#mapstyleSets",
    "method"
  ],
  [
    "src/crud/user.js~user#notifications",
    "class/src/crud/User.js~User.html#instance-method-notifications",
    "src/crud/User.js~User#notifications",
    "method"
  ],
  [
    "src/crud/user.js~user#organisation",
    "class/src/crud/User.js~User.html#instance-method-organisation",
    "src/crud/User.js~User#organisation",
    "method"
  ],
  [
    "src/crud/user.js~user#permissions",
    "class/src/crud/User.js~User.html#instance-method-permissions",
    "src/crud/User.js~User#permissions",
    "method"
  ],
  [
    "src/crud/user.js~user#resourcename",
    "class/src/crud/User.js~User.html#instance-get-resourceName",
    "src/crud/User.js~User#resourceName",
    "member"
  ],
  [
    "src/crud/user.js~user#svgsets",
    "class/src/crud/User.js~User.html#instance-method-svgSets",
    "src/crud/User.js~User#svgSets",
    "method"
  ],
  [
    "src/crud/base/crudbase.js",
    "file/src/crud/base/CrudBase.js.html",
    "src/crud/base/CrudBase.js",
    "file"
  ],
  [
    "src/crud/base/crudbase.js~crudbase#_buildcreatedata",
    "class/src/crud/base/CrudBase.js~CrudBase.html#instance-method-_buildCreateData",
    "src/crud/base/CrudBase.js~CrudBase#_buildCreateData",
    "method"
  ],
  [
    "src/crud/base/crudbase.js~crudbase#_listresource",
    "class/src/crud/base/CrudBase.js~CrudBase.html#instance-method-_listResource",
    "src/crud/base/CrudBase.js~CrudBase#_listResource",
    "method"
  ],
  [
    "src/crud/base/crudbase.js~crudbase#constructor",
    "class/src/crud/base/CrudBase.js~CrudBase.html#instance-constructor-constructor",
    "src/crud/base/CrudBase.js~CrudBase#constructor",
    "method"
  ],
  [
    "src/crud/base/crudbase.js~crudbase#delete",
    "class/src/crud/base/CrudBase.js~CrudBase.html#instance-method-delete",
    "src/crud/base/CrudBase.js~CrudBase#delete",
    "method"
  ],
  [
    "src/crud/base/crudbase.js~crudbase#restore",
    "class/src/crud/base/CrudBase.js~CrudBase.html#instance-method-restore",
    "src/crud/base/CrudBase.js~CrudBase#restore",
    "method"
  ],
  [
    "src/crud/base/crudbase.js~crudbase#save",
    "class/src/crud/base/CrudBase.js~CrudBase.html#instance-method-save",
    "src/crud/base/CrudBase.js~CrudBase#save",
    "method"
  ],
  [
    "src/crud/base/crudsetbase.js",
    "file/src/crud/base/CrudSetBase.js.html",
    "src/crud/base/CrudSetBase.js",
    "file"
  ],
  [
    "src/crud/base/crudsetbase.js~crudsetbase#_child",
    "class/src/crud/base/CrudSetBase.js~CrudSetBase.html#instance-get-_Child",
    "src/crud/base/CrudSetBase.js~CrudSetBase#_Child",
    "member"
  ],
  [
    "src/crud/base/crudsetbase.js~crudsetbase#items",
    "class/src/crud/base/CrudSetBase.js~CrudSetBase.html#instance-method-items",
    "src/crud/base/CrudSetBase.js~CrudSetBase#items",
    "method"
  ],
  [
    "src/crud/base/resourcebase.js",
    "file/src/crud/base/ResourceBase.js.html",
    "src/crud/base/ResourceBase.js",
    "file"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#api",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-api",
    "src/crud/base/ResourceBase.js~ResourceBase#api",
    "member"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#baseurl",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-baseUrl",
    "src/crud/base/ResourceBase.js~ResourceBase#baseUrl",
    "member"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#constructor",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-constructor-constructor",
    "src/crud/base/ResourceBase.js~ResourceBase#constructor",
    "method"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#fieldnames",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-fieldNames",
    "src/crud/base/ResourceBase.js~ResourceBase#fieldNames",
    "member"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#ownable",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-ownable",
    "src/crud/base/ResourceBase.js~ResourceBase#ownable",
    "member"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#refresh",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-method-refresh",
    "src/crud/base/ResourceBase.js~ResourceBase#refresh",
    "method"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#resourcename",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-resourceName",
    "src/crud/base/ResourceBase.js~ResourceBase#resourceName",
    "member"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#resourcepath",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-resourcePath",
    "src/crud/base/ResourceBase.js~ResourceBase#resourcePath",
    "member"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#tostring",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-method-toString",
    "src/crud/base/ResourceBase.js~ResourceBase#toString",
    "method"
  ],
  [
    "src/crud/base/resourcebase.js~resourcebase#url",
    "class/src/crud/base/ResourceBase.js~ResourceBase.html#instance-get-url",
    "src/crud/base/ResourceBase.js~ResourceBase#url",
    "member"
  ],
  [
    "src/crud/index.js",
    "file/src/crud/index.js.html",
    "src/crud/index.js",
    "file"
  ],
  [
    "src/errors/abstracterror.js",
    "file/src/errors/AbstractError.js.html",
    "src/errors/AbstractError.js",
    "file"
  ],
  [
    "src/errors/abstracterror.js~abstractclasserror#constructor",
    "class/src/errors/AbstractError.js~AbstractClassError.html#instance-constructor-constructor",
    "src/errors/AbstractError.js~AbstractClassError#constructor",
    "method"
  ],
  [
    "src/errors/abstracterror.js~abstractmethoderror#constructor",
    "class/src/errors/AbstractError.js~AbstractMethodError.html#instance-constructor-constructor",
    "src/errors/AbstractError.js~AbstractMethodError#constructor",
    "method"
  ],
  [
    "src/errors/apierror.js",
    "file/src/errors/ApiError.js.html",
    "src/errors/ApiError.js",
    "file"
  ],
  [
    "src/errors/apierror.js~apierror#code",
    "class/src/errors/ApiError.js~ApiError.html#instance-get-code",
    "src/errors/ApiError.js~ApiError#code",
    "member"
  ],
  [
    "src/errors/apierror.js~apierror#constructor",
    "class/src/errors/ApiError.js~ApiError.html#instance-constructor-constructor",
    "src/errors/ApiError.js~ApiError#constructor",
    "method"
  ],
  [
    "src/errors/apierror.js~apierror#message",
    "class/src/errors/ApiError.js~ApiError.html#instance-get-message",
    "src/errors/ApiError.js~ApiError#message",
    "member"
  ],
  [
    "src/errors/apierror.js~apierror#tostring",
    "class/src/errors/ApiError.js~ApiError.html#instance-method-toString",
    "src/errors/ApiError.js~ApiError#toString",
    "method"
  ],
  [
    "src/errors/apierror.js~apierror#type",
    "class/src/errors/ApiError.js~ApiError.html#instance-get-type",
    "src/errors/ApiError.js~ApiError#type",
    "member"
  ],
  [
    "src/errors/nodeerror.js",
    "file/src/errors/NodeError.js.html",
    "src/errors/NodeError.js",
    "file"
  ],
  [
    "src/errors/oautherror.js",
    "file/src/errors/OAuthError.js.html",
    "src/errors/OAuthError.js",
    "file"
  ],
  [
    "src/errors/oautherror.js~oautherror#constructor",
    "class/src/errors/OAuthError.js~OAuthError.html#instance-constructor-constructor",
    "src/errors/OAuthError.js~OAuthError#constructor",
    "method"
  ],
  [
    "src/errors/oautherror.js~oautherror#error",
    "class/src/errors/OAuthError.js~OAuthError.html#instance-get-error",
    "src/errors/OAuthError.js~OAuthError#error",
    "member"
  ],
  [
    "src/errors/oautherror.js~oautherror#message",
    "class/src/errors/OAuthError.js~OAuthError.html#instance-get-message",
    "src/errors/OAuthError.js~OAuthError#message",
    "member"
  ],
  [
    "src/errors/oautherror.js~oautherror#tostring",
    "class/src/errors/OAuthError.js~OAuthError.html#instance-method-toString",
    "src/errors/OAuthError.js~OAuthError#toString",
    "method"
  ],
  [
    "src/errors/staticclasserror.js",
    "file/src/errors/StaticClassError.js.html",
    "src/errors/StaticClassError.js",
    "file"
  ],
  [
    "src/errors/unsupportedcruderror.js",
    "file/src/errors/UnsupportedCrudError.js.html",
    "src/errors/UnsupportedCrudError.js",
    "file"
  ],
  [
    "src/errors/validationerror.js",
    "file/src/errors/ValidationError.js.html",
    "src/errors/ValidationError.js",
    "file"
  ],
  [
    "src/errors/validationerror.js~validationerror#constructor",
    "class/src/errors/ValidationError.js~ValidationError.html#instance-constructor-constructor",
    "src/errors/ValidationError.js~ValidationError#constructor",
    "method"
  ],
  [
    "src/errors/validationerror.js~validationerror#tostring",
    "class/src/errors/ValidationError.js~ValidationError.html#instance-method-toString",
    "src/errors/ValidationError.js~ValidationError#toString",
    "method"
  ],
  [
    "src/errors/validationerror.js~validationerror#validationerrors",
    "class/src/errors/ValidationError.js~ValidationError.html#instance-get-validationErrors",
    "src/errors/ValidationError.js~ValidationError#validationErrors",
    "member"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/oauth/dummyflow.js",
    "file/src/oauth/DummyFlow.js.html",
    "src/oauth/DummyFlow.js",
    "file"
  ],
  [
    "src/oauth/dummyflow.js~dummyflow#authenticate",
    "class/src/oauth/DummyFlow.js~DummyFlow.html#instance-method-authenticate",
    "src/oauth/DummyFlow.js~DummyFlow#authenticate",
    "method"
  ],
  [
    "src/oauth/dummyflow.js~dummyflow#constructor",
    "class/src/oauth/DummyFlow.js~DummyFlow.html#instance-constructor-constructor",
    "src/oauth/DummyFlow.js~DummyFlow#constructor",
    "method"
  ],
  [
    "src/oauth/implicitflow.js",
    "file/src/oauth/ImplicitFlow.js.html",
    "src/oauth/ImplicitFlow.js",
    "file"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_anchorcontainserror",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_anchorContainsError",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_anchorContainsError",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_anchorcontainsoauthresponse",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_anchorContainsOAuthResponse",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_anchorContainsOAuthResponse",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_buildredirecturl",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_buildRedirectUrl",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_buildRedirectUrl",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_cleananchorparams",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_cleanAnchorParams",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_cleanAnchorParams",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_getanchorparams",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_getAnchorParams",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_getAnchorParams",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_geterror",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_getError",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_getError",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#_getoauthanchorparams",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-_getOAuthAnchorParams",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#_getOAuthAnchorParams",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#authenticate",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-method-authenticate",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#authenticate",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#callbackurl",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-member-callbackUrl",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#callbackUrl",
    "member"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#constructor",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-constructor-constructor",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#constructor",
    "method"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#path",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-member-path",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#path",
    "member"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#token",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-member-token",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#token",
    "member"
  ],
  [
    "src/oauth/implicitflow.js~implicitflow#usestate",
    "class/src/oauth/ImplicitFlow.js~ImplicitFlow.html#instance-member-useState",
    "src/oauth/ImplicitFlow.js~ImplicitFlow#useState",
    "member"
  ],
  [
    "src/oauth/implicitflowpopup.js",
    "file/src/oauth/ImplicitFlowPopup.js.html",
    "src/oauth/ImplicitFlowPopup.js",
    "file"
  ],
  [
    "src/oauth/implicitflowpopup.js~implicitflowpopup#authenticate",
    "class/src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.html#instance-method-authenticate",
    "src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup#authenticate",
    "method"
  ],
  [
    "src/oauth/implicitflowpopup.js~implicitflowpopup#constructor",
    "class/src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.html#instance-constructor-constructor",
    "src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup#constructor",
    "method"
  ],
  [
    "src/oauth/implicitflowpopup.js~implicitflowpopup#windowoptions",
    "class/src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.html#instance-member-windowOptions",
    "src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup#windowOptions",
    "member"
  ],
  [
    "src/oauth/implicitflowpopup.js~implicitflowpopup.localstoragekey",
    "class/src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.html#static-get-localStorageKey",
    "src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.localStorageKey",
    "member"
  ],
  [
    "src/oauth/implicitflowpopup.js~implicitflowpopup.popupwindowname",
    "class/src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.html#static-get-popupWindowName",
    "src/oauth/ImplicitFlowPopup.js~ImplicitFlowPopup.popupWindowName",
    "member"
  ],
  [
    "src/oauth/oauth.js",
    "file/src/oauth/OAuth.js.html",
    "src/oauth/OAuth.js",
    "file"
  ],
  [
    "src/oauth/oauth.js~oauth#authenticate",
    "class/src/oauth/OAuth.js~OAuth.html#instance-method-authenticate",
    "src/oauth/OAuth.js~OAuth#authenticate",
    "method"
  ],
  [
    "src/oauth/oauth.js~oauth#authenticated",
    "class/src/oauth/OAuth.js~OAuth.html#instance-get-authenticated",
    "src/oauth/OAuth.js~OAuth#authenticated",
    "member"
  ],
  [
    "src/oauth/oauth.js~oauth#clientid",
    "class/src/oauth/OAuth.js~OAuth.html#instance-member-clientId",
    "src/oauth/OAuth.js~OAuth#clientId",
    "member"
  ],
  [
    "src/oauth/oauth.js~oauth#constructor",
    "class/src/oauth/OAuth.js~OAuth.html#instance-constructor-constructor",
    "src/oauth/OAuth.js~OAuth#constructor",
    "method"
  ],
  [
    "src/oauth/oauth.js~oauth#forget",
    "class/src/oauth/OAuth.js~OAuth.html#instance-method-forget",
    "src/oauth/OAuth.js~OAuth#forget",
    "method"
  ],
  [
    "src/oauth/oauth.js~oauth#host",
    "class/src/oauth/OAuth.js~OAuth.html#instance-member-host",
    "src/oauth/OAuth.js~OAuth#host",
    "member"
  ],
  [
    "src/oauth/oauth.js~oauth#path",
    "class/src/oauth/OAuth.js~OAuth.html#instance-member-path",
    "src/oauth/OAuth.js~OAuth#path",
    "member"
  ],
  [
    "src/oauth/oauth.js~oauth#scopes",
    "class/src/oauth/OAuth.js~OAuth.html#instance-member-scopes",
    "src/oauth/OAuth.js~OAuth#scopes",
    "member"
  ],
  [
    "src/oauth/oauth.js~oauth#token",
    "class/src/oauth/OAuth.js~OAuth.html#instance-member-token",
    "src/oauth/OAuth.js~OAuth#token",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js",
    "file/src/oauth/OAuthToken.js.html",
    "src/oauth/OAuthToken.js",
    "file"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#constructor",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-constructor-constructor",
    "src/oauth/OAuthToken.js~OAuthToken#constructor",
    "method"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#expired",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-get-expired",
    "src/oauth/OAuthToken.js~OAuthToken#expired",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#expires",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-member-expires",
    "src/oauth/OAuthToken.js~OAuthToken#expires",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#save",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-method-save",
    "src/oauth/OAuthToken.js~OAuthToken#save",
    "method"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#scopes",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-member-scopes",
    "src/oauth/OAuthToken.js~OAuthToken#scopes",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#toresponseobject",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-method-toResponseObject",
    "src/oauth/OAuthToken.js~OAuthToken#toResponseObject",
    "method"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#tostring",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-method-toString",
    "src/oauth/OAuthToken.js~OAuthToken#toString",
    "method"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#token",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-member-token",
    "src/oauth/OAuthToken.js~OAuthToken#token",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken#type",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#instance-member-type",
    "src/oauth/OAuthToken.js~OAuthToken#type",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken.fromresponseobject",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#static-method-fromResponseObject",
    "src/oauth/OAuthToken.js~OAuthToken.fromResponseObject",
    "method"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken.nodetokenfilename",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#static-get-nodeTokenFilename",
    "src/oauth/OAuthToken.js~OAuthToken.nodeTokenFilename",
    "member"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken.recover",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#static-method-recover",
    "src/oauth/OAuthToken.js~OAuthToken.recover",
    "method"
  ],
  [
    "src/oauth/oauthtoken.js~oauthtoken.storagename",
    "class/src/oauth/OAuthToken.js~OAuthToken.html#static-get-storageName",
    "src/oauth/OAuthToken.js~OAuthToken.storageName",
    "member"
  ],
  [
    "src/oauth/passwordflow.js",
    "file/src/oauth/PasswordFlow.js.html",
    "src/oauth/PasswordFlow.js",
    "file"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#authenticate",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-method-authenticate",
    "src/oauth/PasswordFlow.js~PasswordFlow#authenticate",
    "method"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#constructor",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-constructor-constructor",
    "src/oauth/PasswordFlow.js~PasswordFlow#constructor",
    "method"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#password",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-get-password",
    "src/oauth/PasswordFlow.js~PasswordFlow#password",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#password",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-set-password",
    "src/oauth/PasswordFlow.js~PasswordFlow#password",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#path",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-get-path",
    "src/oauth/PasswordFlow.js~PasswordFlow#path",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#path",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-set-path",
    "src/oauth/PasswordFlow.js~PasswordFlow#path",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#secret",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-get-secret",
    "src/oauth/PasswordFlow.js~PasswordFlow#secret",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#secret",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-set-secret",
    "src/oauth/PasswordFlow.js~PasswordFlow#secret",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#token",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-member-token",
    "src/oauth/PasswordFlow.js~PasswordFlow#token",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#username",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-set-username",
    "src/oauth/PasswordFlow.js~PasswordFlow#username",
    "member"
  ],
  [
    "src/oauth/passwordflow.js~passwordflow#username",
    "class/src/oauth/PasswordFlow.js~PasswordFlow.html#instance-get-username",
    "src/oauth/PasswordFlow.js~PasswordFlow#username",
    "member"
  ],
  [
    "src/oauth/statecontainer.js",
    "file/src/oauth/StateContainer.js.html",
    "src/oauth/StateContainer.js",
    "file"
  ],
  [
    "src/traits/handlesimages.js",
    "file/src/traits/HandlesImages.js.html",
    "src/traits/HandlesImages.js",
    "file"
  ],
  [
    "src/traits/handlesimages.js~handlesimages#imagehandler",
    "class/src/traits/HandlesImages.js~HandlesImages.html#instance-get-imageHandler",
    "src/traits/HandlesImages.js~HandlesImages#imageHandler",
    "member"
  ],
  [
    "src/traits/ownableresource.js",
    "file/src/traits/OwnableResource.js.html",
    "src/traits/OwnableResource.js",
    "file"
  ],
  [
    "src/traits/ownableresource.js~ownableresource#attachorganisations",
    "class/src/traits/OwnableResource.js~OwnableResource.html#instance-method-attachOrganisations",
    "src/traits/OwnableResource.js~OwnableResource#attachOrganisations",
    "method"
  ],
  [
    "src/traits/ownableresource.js~ownableresource#organisations",
    "class/src/traits/OwnableResource.js~OwnableResource.html#instance-method-organisations",
    "src/traits/OwnableResource.js~OwnableResource#organisations",
    "method"
  ],
  [
    "src/traits/ownableresource.js~ownableresource#ownable",
    "class/src/traits/OwnableResource.js~OwnableResource.html#instance-get-ownable",
    "src/traits/OwnableResource.js~OwnableResource#ownable",
    "member"
  ],
  [
    "src/traits/ownableresource.js~ownableresource#syncorganisations",
    "class/src/traits/OwnableResource.js~OwnableResource.html#instance-method-syncOrganisations",
    "src/traits/OwnableResource.js~OwnableResource#syncOrganisations",
    "method"
  ],
  [
    "src/traits/ownableresource.js~ownableresource#unlinkorganisations",
    "class/src/traits/OwnableResource.js~OwnableResource.html#instance-method-unlinkOrganisations",
    "src/traits/OwnableResource.js~OwnableResource#unlinkOrganisations",
    "method"
  ],
  [
    "src/traits/trait.js",
    "file/src/traits/Trait.js.html",
    "src/traits/Trait.js",
    "file"
  ],
  [
    "src/utils/singleton.js",
    "file/src/utils/Singleton.js.html",
    "src/utils/Singleton.js",
    "file"
  ],
  [
    "src/utils/singleton.js~singleton#constructor",
    "class/src/utils/Singleton.js~Singleton.html#instance-constructor-constructor",
    "src/utils/Singleton.js~Singleton#constructor",
    "method"
  ],
  [
    "src/utils/staticclass.js",
    "file/src/utils/StaticClass.js.html",
    "src/utils/StaticClass.js",
    "file"
  ],
  [
    "src/utils/staticclass.js~staticclass#constructor",
    "class/src/utils/StaticClass.js~StaticClass.html#instance-constructor-constructor",
    "src/utils/StaticClass.js~StaticClass#constructor",
    "method"
  ],
  [
    "src/utils/caseconverter.js",
    "file/src/utils/caseConverter.js.html",
    "src/utils/caseConverter.js",
    "file"
  ],
  [
    "src/utils/helpers.js",
    "file/src/utils/helpers.js.html",
    "src/utils/helpers.js",
    "file"
  ],
  [
    "src/utils/node.js",
    "file/src/utils/node.js.html",
    "src/utils/node.js",
    "file"
  ],
  [
    "src/utils/reflection.js",
    "file/src/utils/reflection.js.html",
    "src/utils/reflection.js",
    "file"
  ],
  [
    "src/utils/requests.js",
    "file/src/utils/requests.js.html",
    "src/utils/requests.js",
    "file"
  ],
  [
    "src/utils/uuid.js",
    "file/src/utils/uuid.js.html",
    "src/utils/uuid.js",
    "file"
  ]
]